# Generated by Django 4.2.16 on 2024-10-29 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('birth_day', models.DateField(blank=True, null=True)),
                ('gender', models.BooleanField(default=True)),
                ('avatar', models.ImageField(blank=True, default='images/avatars/avatar_default.png', null=True, upload_to='images/avatars/')),
                ('is_normal_user', models.BooleanField(default=False)),
                ('is_expert', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_w_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
