# Generated by Django 4.2.16 on 2024-11-03 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0002_profile_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('imgUrl', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('navigationPath', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('imgUrl', models.ImageField(blank=True, null=True, upload_to='emergency_elp_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('jobTitle', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('imgUrl', models.URLField(max_length=500)),
                ('isFavorite', models.BooleanField(default=False)),
                ('rating', models.FloatField()),
                ('reviews', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_w_expert', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
