# Generated by Django 4.2.16 on 2024-11-03 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category_emergencyhelp_expert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='imgUrl',
        ),
    ]
