# Generated by Django 4.2.16 on 2024-11-03 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_expert_imgurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='isFavorite',
        ),
    ]
