# Generated by Django 4.2.16 on 2024-11-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_expert_isfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='bio',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
