# Generated by Django 4.2.16 on 2024-11-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_knowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='experts/'),
        ),
    ]
