# Generated by Django 4.2.16 on 2024-11-23 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_stories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_w_knowledge', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
