# Generated by Django 4.2.16 on 2024-11-23 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_message_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatechat',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_as_user1', to='api.profile'),
        ),
        migrations.AlterField(
            model_name='privatechat',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_as_user2', to='api.profile'),
        ),
    ]
