# Generated by Django 4.2.16 on 2024-12-01 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_privatechat_user1_alter_privatechat_user2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stories',
            name='user',
        ),
        migrations.AddField(
            model_name='stories',
            name='profile',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile_w_stories', serialize=False, to='api.profile'),
            preserve_default=False,
        ),
    ]
